### ISSUE TITLE
OZWave Plugin: RaZberry Controller (ZWave.me) can't initialize...

### ISSUE THREAD

**Issue by massimo1980** [Nico0084/domogik-plugin-ozwave#23]
Hi there,
( first of all, really congrats for your work!! ...and sorry for my poor english! )
Sorry if i've choose the wrong place to ask help ( pls let me know where i can post this )
Actually i'm tryin to configure the Razberry zwave controller on a Raspberry Pi3 with Domogik 0.4
I've correctly created the udev rule for the device and installed python-openzwave 
( for testing the correct installation, i've also installed "OpenZWave Control Panel" that seems to correctly initialize the device....get the NetID ...and do the other actions/stuff )
Once installed the plugin, i've noticed that the only way to get it to "ALIVE" status was to set the NetworkID associated to the device ( taken from the ozwcp previously installed ) -->

http://pastebin.com/LEGskheQ

On the log files didn't noticed nothing about, the plugin continue to remain in "domogik-ozwave DEBUG Send client status : alive"
So, i've tryid to run it via command line to see more verbose logs: --->

http://pastebin.com/xwTCDswE

But everything i've tryed to do, always returns this exception:
Exception in thread th_Start_open_drivers:

Sorry again if i've chosen the wrong place to ask!!!!

Thanks!

**Comment by Nico0084** [comment]
Hi Massimo,

It' a versioning issue between plugin 0.4 and python-openzwave version
0.3.0b9 ( and openzwave c++ lib)
There is some Unicode change in b9.
Try with python-openzwave version 0.3.0b8, it's should be work.

2016-05-02 9:35 GMT+02:00 massimo1980 <notifications@github.com>:

**Comment by massimo1980** [comment]
Hi Nico,
thanks for the quick answer!!!!
I've followed your advice downgrading the python-openzwave to 0.3.0b8
( ...after building e installing ....i get a weird error from the domogik admin interface sayin that "i have no component installed.....either the core ones! .....but after some log reading i've found that WTForms package were upgraded by the python-openzwave script [ and ...not from "pip" ...but from OS] )
Anyway .....this was the result ---> http://pastebin.com/AFrQk4CS

Nothing seems to change :(

**Comment by Nico0084** [comment]
Sorry, I had check commit change and utf8 modification is before b8.
I think it's commit on 5 may 2015 who make this change.
I don't remember witch beta is.
I don't work on plugin rev 0.4.
But I think a simple fix can be do.
I'll try to do it in next day.
Le 2 mai 2016 2:36 PM, "massimo1980" <notifications@github.com> a écrit :

Hi Nico,
thanks for the quick answer!!!!
I've followed your advice downgrading the python-openzwave to 0.3.0b8
( ...after building e installing ....i get a weird error from the domogik
admin interface sayin that "i have no component installed.....either the
core ones! .....but after some log reading i've found that WTForms package
were upgraded by the python-openzwave script [ and ...not from "pip" ...but
from OS] )
Anyway .....this was the result ---> http://pastebin.com/AFrQk4CS

Nothing seems to change :(

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/Nico0084/domogik-plugin-ozwave/issues/23#issuecomment-216224217>

**Comment by massimo1980** [comment]
really appreciate your support!
i'll stay with my eyes on this thread waiting for your fix!

**Comment by tikismoke** [comment]
Did you say you run Domogik 0.4?
Have you try with the dev branch of Domogik?(the next 0.5)

Just to know

**Comment by massimo1980** [comment]
after hours of hell's flame i've installed the devel version but....same story...

P.S. What did you mean with "I don't work on plugin rev 0.4." 
i've found only this release
( ...sorry if is a dumb question! )

**Comment by tikismoke** [comment]
Meaning Domogik in dev branch from git and the plugin from git Dev branch too?

**Comment by Nico0084** [comment]
If you install domogik 0.5 (git develop branche) and the plugin 0.5
(develop also) keep python openzwave 0.3.0b8
Because in b9 and 0.3 there is some group association change that not
reporting to plugin for the moment.
So you should have an exception.

**Comment by massimo1980** [comment]
just done.
this is the log:   http://pastebin.com/j7C8XcUg

can't understand why can't open the serial port

**Comment by massimo1980** [comment]
Ok....with DEV branched of domogik, domogik-mq and ozwave plugin ...seems to work fine!!!
great job guys!!

**Comment by tikismoke** [comment]
Crap forget MQ in dev too...

Le 3 mai 2016 10:23:03 GMT+02:00, massimo1980 <notifications@github.com> a écrit :
>Ok....with DEV branched of domogik, domogik-mq and ozwave plugin
>...seems to work fine!!!
>great job guys!! 
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Nico0084/domogik-plugin-ozwave/issues/23#issuecomment-216466161

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by massimo1980** [comment]
sometime i have the feel that you don't read me at all 😆 
I've just installed everything from the dev branch and get domogik to work....and the zwave device too...
there are only few little things about the device association and identification
My Aeotec 4in1 sensor can't be initialized but seems to send values...
well....not so corret value ...it says that there are 140°C ....but it's a dev version...dev plugin ..so it's ok
I think that can be helpfull for the others to add in the documentation the "raspberry user permission grant" ( usermod -a -G dialout domogik )...but it's all up to you obviously
I've just tried to do the same with 0.4 version and it works as well

**Comment by massimo1980** [comment]
actually i'm tryin to configure my Aeotec 4in1 Multisensor 
( i was unable to associate it throught the plugin .....i was forced to use the openzwave interface )
in the "Nodes" section of the "Advanced" tab i can see my sensor row
but there is always the little green gear spinning sayin: In Progress - Device initializing ( wait to retrive config parameters )   -> https://imagebin.ca/v/2gLs5ZxY4HzR

and in the CLASS_COMMAND list i can't modify any parameters -> https://imagebin.ca/v/2gLsoE5JHxAb

have i missed something ? wrong device config?

**Comment by massimo1980** [comment]
After a week waiting for an answer i've decided to swith to OpenHAB
It's really impossible for people like me to "test" an application without community support and this "gigantic lack" of documentation
Best Regards

**Comment by tikismoke** [comment]
Maybe people had vacation ;)

**Comment by massimo1980** [comment]
look how fast answers arrives when someone make criticism

**Comment by bibi21000** [comment]
>but after some log reading i've found that WTForms package were upgraded by the python-openzwave script [ and ...not from "pip" ...but from OS] )
Where did you find that ?

**Comment by fritz-smh** [comment]
@massimo1980 I did not follow at all this issue. And I am not in charge of this plugin. But I find your 2 last comments quite not cool!
Domogik and this plugin are open sources projects done by people on their free time. Having no response during one week on an open source project is not a shame! Of course some bigger projects could respond quicker! But we are still a little project.

Seeing the various comments of people in this issue, you can't say that there is no community support. About the "gigantic lack of doc", yes, there are things to improve, but this is not a reason to be such rude !

The zwave plugin is still in dev, Domogik is still in 0.x release, so you can't wait for a finish product yet.

If you want a 24h support, just go on commercial solutions.

Just to finish, the response of Tiki after you criticism is not a response because of your cristicism, but to notice you that nico is maybe in holiday. Just read what people are writing before being so rude again !

Best regards,
Fritz

PS : it seems OpenHab is also a good solution, I hope you will be happy with it and its community.

**Comment by Nico0084** [comment]
@massimo1980

Say as Fritz we are open source developper with a family and many others occupations. This last weeks I was very busy at home and work and no time to develop and do support.

For your problem, your log (openzwave log) show a zwave communication problem. it's not a faillur plugin.
Controller try to send message to node 8 but it doesnt respond. After 3 try it put node 8 as fail, so the only way it's to force communication from the node himself.
I don't known how OpenHab work but for ozwave plugin, at each start it try to get all parameters directly from the node. If there is no response it show parameters who are not reload in values node table (admin tab) and set node icon status as Waiting parameters but it's not a problem for node working, just an information.
The values of parameters are display from the config file saved by openzwave (the last value get)
I'm not sure OpenHab have this functionality, so in this case it show saved value (probably good) but not a value read recently from node.

Best regard.
Nico

**Comment by Nico0084** [comment]
@massimo1980

Thank's for your domogik user dialout group permission suggestion. It's add in doc for next push :)

I had look with more care your openzwave log. it' curious
* 1st point :  you give a picture (https://imagebin.ca/v/2gLs5ZxY4HzR) for node 2, and openzwave log (http://pastebin.com/Leae0BDS ) is for node 8 ????
* 2nd point : in log, your node 8 have a good response and suddenly response take o lot of time (line 44: Response RTT 1799) to finally stop response !
* 3td point : Node 8 has battery command class so it's must be a sleeping device. In this case it could be normal to have no response if it sleep. But openwave consider it as a non sleeping node. Don't known why, you must check all init log to try to get answer.

Perhaps an bad inclusion process could be origin, if your problem persists do an exclusion before inclusion.
It could be a low battery issue also or a bad configuration parameter if you power it by current, Check the constructor documentation.

Best regard.
Nico

**Comment by massimo1980** [comment]
@Nico0084 
1st: yep the log and the image were taken in different moment ( after various try ). It was only to let you understand what the issue was
2nd: I've tried different way with that sensor.....with battery...without....but always the same responses
3td: as for the second point... After a day of tryin, I bought a new sensor ( only temperature sensor ) 
       but after the initialization ....same result. After switching to OpenHab i've tried the same operations on the new platform and i didn't get that type of error. In a week i'll get a new raspi and try to repeat all the steps ( hoping to help you in some way )

@fritz-smh
I'm sorry if you find my last 2 comments "too rude" but i only gave my opinion ( it was not my intention to give you the wrong emotional side...but i've started the discussion sayin "sorry for my poor english"...so it was my fault to not explain well the point and i say sorry for that .....but this remain a "state of art" ). I don't think this is the right place to make "moralisms" but i have to answer you on 2 point:
- "If you want a 24h support, just go on commercial solutions." ----> I don't get where you read this or where i wrote to "pretend" a technical solution....i only said "answer"....that mean for example "ok i'll take a look"     
- "Just to finish, the response of Tiki after you criticism is not a response because of your cristicism, but to notice you that nico is maybe in holiday. Just read what people are writing before being so rude again !"    ----->    instead......the answer Tiki gave me was ok ? ("Meaning Domogik in dev branch from git and the plugin from git Dev branch too?") <-- Yes, I think that "read what people write" it's a good advice ...hoping that everyone follow this!

Thanks for your support and for all the answer 
I have put "domogik" in standby for now but i'll give you feeds as soon as i'll take the app running

Best Regards
