### ISSUE TITLE
Could not get it started...

### ISSUE THREAD

**Issue by cboutelier** [Nico0084/domogik-plugin-ozwave#26]
Hello dear,
I have successfully installed the ozwave libs on my raspberry p-zero, Python openzwave is ok as well, I could run the small apps coming along. I installed the domogik plugin from the extracted package using dmg_package install, did the configuration but for some reasons I keep getting the starting status.
I checked the logs xplplugin_ozwave.log and all possible logs in the same folder without success.
Is there something else I could check?

**Comment by Nico0084** [comment]
Hi
I suppose you use domogik 0.4 ?
Please post your xplplugin_ozwave.log with debug active (set in /etc/domogik/domogik.cfg). I will have a look.

**Comment by cboutelier** [comment]
Hi,
As a matter of fact yes, I do use the latest revision of domogik.
[xplplugin_ozwave.txt](https://github.com/Nico0084/domogik-plugin-ozwave/files/526184/xplplugin_ozwave.txt)

**Comment by Nico0084** [comment]
Plugin stop init progress. Perhaps due to access rights on "/var/lib/domogik/domogik_packages/plugin_ozwave/data" directory.
Check if your domogik user has write access to it 
If not do : sudo chmod +w /var/lib/domogik/domogik_packages/plugin_ozwave/data

Other way his to try start plugin in terminal mod, go to "/var/lib/domogik/domogik_packages/plugin_ozwave/" and run with domogik user "start.sh". You should see potential exception.

You can post terminal result to check it.

**Comment by cboutelier** [comment]
Very good, it works!
I had to create the data folder in the plugin_ozwave package. I set domogik as the owner with write permission. Restarted and voila!
Maybe such a folder should have been created in the installation procedure.
Thank you for your fast and efficient support.

**Comment by tikismoke** [comment]
Nico to be sure and do the same in my plugin.

Does the commit create the data dir or just log the problems?

**Comment by Nico0084** [comment]
Yes, try to create data dir and if it don't have write access it log problem.
https://github.com/Nico0084/domogik-plugin-ozwave/blob/0.4.0b1/lib/ozwave.py#L127

You must also catch possible exception of **get_data_files_directory** and get manualy data path : https://github.com/Nico0084/domogik-plugin-ozwave/blob/0.4.0b1/bin/ozwave.py#L77

**Comment by tikismoke** [comment]
Ok thank's i'll had this in my to-do list ;)
