### ISSUE TITLE
add danfoss thermostat

### ISSUE THREAD

**Issue by tikismoke** [Nico0084/domogik-plugin-ozwave#3]
Hi nico,
When the 0.4 will have stable plugin need for my home i'm going to migrate.
But before and to help:
I'll have a danfoss themosat (014G0013) and S2 stick.
I have planned to try domogik and ozwave this WE on a rpi 2.
If you could have a look before, not knowing how to add new device type in your plugin.
If needed i can install other software and give ssh access to debug when all will be ready.

**Comment by Nico0084** [comment]
Hi  tiki
Thanks for help
For now plugin is not really ready to final user
But for test it must work (wait next commit, I have change some xpl parameters,  devices must be recreate )
Almost basic commands and sensors are in the json.
Juste need to create device_type to your living connect
I 'll create it for next commit
I never use this plug in with hardware, so if you can try :)
I'm confident that work.
On waiting you can install python-openawave 1.3b4 on rpi2. I could take some time !

**Comment by tikismoke** [comment]
battery state appears (not the right but that's another pb) but no setpoint value (but not sure the controller and thermostat are talking due to distance).

**Comment by Nico0084** [comment]
Essais de récréer ton device avec le fix #6. le setpoint devrait marcher.
Si le battery state est mis à jour, c'est que le controlleur doit arriver a communiqué avec.

**Comment by tikismoke** [comment]
Pareil avec la dernieres version, par contre le setpoint apparaiisent bien dans advanced nodes:
1 decimal 24 C	COMMAND_CLASS_THERMOSTAT_SETPOINT	1	Heating 1	User

**Comment by tikismoke** [comment]
Les changements de valeur par la commande ne fonctionne pas non plus.
En revanche depuis l'onglet nodes dans advacend c'est bon. Au réveil le périph pren la bonne valeur.

**Comment by tikismoke** [comment]
Je confirme, ça marche super.

Merci nico0084
