### ISSUE TITLE
new device: fibaro smoke sensor FGSS101

### ISSUE THREAD

**Issue by piratebab** [Nico0084/domogik-plugin-ozwave#31]
serait il possible d'ajouter la prise en compte de ce device

**Comment by tikismoke** [comment]
Pour moi il y est non?

**Comment by piratebab** [comment]
pas complètement, je ne peux pas créer de widget. Voici ce que j'ai
https://pix.debian-fr.xyz/?img=1485540562.png

python-openzwave version 0.3.1 , 1.4.252

**Comment by tikismoke** [comment]
Ha j'ai confondu avec celui que j'ai:
FIBARO System -- FGSD002 Smoke Sensor
Sinon si y a un bouton + qui apparait tu peut t'en servir pour pré-remplir u ticket github avec les infos du devices.

**Comment by Nico0084** [comment]
Il faut que tu réveil ton device pour qu' openzwave récupère toutes les
valeurs possibles et le reconnaisse entièrement
Ensuite tu devrais avoir accès à là possibilité de créer une demande de
nouveau device via une issue sur github
Sans tous les paramètres du device il n'est pas possible de créer un
product domogik.
C'est le souci des devices zwave sur batterie. Ils ne communique pas sans
réveil,  certains arrivent à tout transmettre lors de l'inclusion mais ça
passe pas à tout les coups.
Bonne manip.
En attendant du nouveau
++

**Comment by piratebab** [comment]
J'ai déja fait plusieurs "zwave communication test", ainsi que des "sensoe reset", mais pas de changement.
Le type de sensor est bien reconnu, mais pas suffisament pour créer le widget.
Malgres l'indication: current stage: complete.
Et j'ai accés à tous les paramètres

**Comment by piratebab** [comment]
la doc du capteur indique:
"Default setting: 14400 (each 4h)
When the Smoke Sensor is in battery power mode you can set up the wake up time
based in seconds. At each wake up, a the Smoke Sensor communicates with the
main controller, updates parameters settings and the software if necessary. The
Smoke Sensor will wake up at defined time interval and will ALWAYS try to
communicate with the main controller. After each failed communication attempt,
the sensor will retry to establish connection with the main controller after 60
seconds. After 3 failed attempts, the lack of the Z-Wave range alarm will be
triggered. The parameter is relevant for the battery powering mode only. Longer
time interval means less frequent communication and thus a longer battery life.
The Z-Wave range alarm will be cancelled automatically, after first successfull
connection.
"
Comme je n'ai pas de clignotement rose de la LED, il n'y a donc pas d'erreur de communication, et donc le capteur se réveille toute les 4 heures

**Comment by Nico0084** [comment]
Il va me falloir plus d'info que ça pour être sur que l'on se comprenne ;)

Dans un premier temps il me faut les datas du device. Dans l'idéale il
faudrait que le log openzwave soit activé (voir
http://domogik-plugin-ozwave.readthedocs.io/en/develop/ozwave.html#configuration
)
Ensuite que tu active le Monitoring du node depuis la table des nodes : 
![image](https://cloud.githubusercontent.com/assets/4672142/22416522/53686b4e-e6cf-11e6-9350-b43b44a248dc.png)


L'idéale est de capturer un reveil une détection incendie durant le
monitoring, tu peux donc le laisser tourner un peu.
Ensuite tu joint ton fichier
/var/lib/domogik/domogik_packages/plugin_ozwave/data/<ton_networkID_nodeID.log
à l'issue

J'aurais un max de détails comme ça :)
@+
Nico

2017-01-29 20:50 GMT+01:00 piratebab <notifications@github.com>:

**Comment by piratebab** [comment]
ok, je fais ça dans la semaine

**Comment by piratebab** [comment]
log du device (expire dans 6 jours)

https://paste.debian-fr.xyz/?22ab52020fb945b2#/+/wh89tIomJxv7SCP/ERwhN5y5wLjHAVLrVmdaa1gM=


log domogik (expire dans 6 jours)

https://paste.debian-fr.xyz/?89fd696b58d01243#Bivpt1jkNBDmBHXtV7NgpdG+DEVa6L9u2jEYlvDEJ8g=

**Comment by Nico0084** [comment]
heu il demande un mot de passe pour le 2ème !

2017-01-30 20:27 GMT+01:00 piratebab <notifications@github.com>:

**Comment by piratebab** [comment]
je retente
https://paste2.org/aJ5YX1Jf

**Comment by Nico0084** [comment]
Mise à jour du plugin en develop :
Stop du plugin
avec le user domogik :
dmg_package -u
https://github.com/Nico0084/domogik-plugin-ozwave/archive/develop.zip
restart du plugin

2017-01-30 22:01 GMT+01:00 piratebab <notifications@github.com>:

**Comment by piratebab** [comment]
La mise à jour à résolu le probleme de détection incomplete du device.
La demande de création du widget a pu étre faites via l'interface de domoweb
https://github.com/Nico0084/domogik-plugin-ozwave/issues/34
