### ISSUE TITLE
Can't start from admin

### ISSUE THREAD

**Issue by tikismoke** [Nico0084/domogik-plugin-ozwave#4]
My problem was that i use 0x0184e15f as networdid and homeid in my controller when creating it.

Deleting it and creating a new one with networdid=mynetworkid and homeid=0x0184e15f allow the plugin to start from admin.

**Comment by Nico0084** [comment]
Il ni a plus besoin de connaitre le homeid, le plugin le trouve automatiquement et fait le lien.
Le parametre networkid est totalement indépendant du homeId, comme ça si le homeId change il ne faut pas recréer les devices.
Tu peux mettre ce que tu veux (enfin pas d'accent ni espace (pas testé))
Donc maintenant le plugin démarre depuis l'admin, c'est ça ?

**Comment by tikismoke** [comment]
Oui le souci venait d'une erreur (comme tu l'a dit genre accent). Il doit y avoir une exception ou je sais pas quoi si on ne mets pas quelquechose de correct en gros.
