### ISSUE TITLE
New install : create data folder and info.json file

### ISSUE THREAD

**Issue by mattboll** [Nico0084/domogik-plugin-ozwave#40]
Hi,
on a new installation, I had to manually create the data folder (I didn't remember where it was, please ask me if it's needed)
I also had to copy info.json file and give rights to domogik user.
May be you should use this function (see @fritz-smh for details) https://gist.github.com/fritz-smh/f9cbfe05e5ff5094d2001225e993b9de

**Comment by Nico0084** [comment]
You can find data folder in /var/lib/domogik/domogik_packages/plugin_ozwave
User used by domogik (default "domogik") must have write access to create it and put data in.

plugin use get_data_files_directory methode and log an error if it can't create it.
So I presum you have an error in plugin_ozwave.log.
Probably the same issue #26 .

I think you had do install with an other user than domogik. so folder access may induce potentiel issue.
You must install plugin (dmg_package) with domogik user
