### ISSUE TITLE
Device type

### ISSUE THREAD

**Issue by tikismoke** [Nico0084/domogik-plugin-ozwave#9]
Don't know if it's really a bug.

All (at least most) of domogik device type in plugins start with the plugin name and a point "."
onewire.gpio
diskfree.disk_usage
mqtt.voltage

Think's in ozwave it should be the same:
ozwave.switch
ozwave.node
.....

Not sure it's a real rules.
It as introduce a bug in domodroid (solved easily).

To be discuss with devs.

**Comment by Nico0084** [comment]
It could be a good thing, the downside is to extend the name of device_type (device_type_id)
The Information of plugin who creates  device is nevertheless in the db:
table "core_device" key "client_id".
So it's just a rule to have a standard in different json not a real need.

If device_type_id must builded with a rule like pluginName.xxx format, the doc does not specify it clearly.
We should add it.

We need to handle multi dot in device_type_id like : ozwave.switch.power.energy.meter

**Comment by Nico0084** [comment]
After team discussion
No needs on domogik side and fixed in domodroid.
